name: Sync Notion to GitHub
author: YouXam
branding:
  icon: 'arrow-down-circle'
  color: 'blue'
description: 'This is a GitHub Action that syncs Notion to GitHub.'
inputs:
  notion_token:
    description: 'The notion api token.'
    required: true
  author:
    description: "Articles's author. If left blank, then get from notion."
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: "github"

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: 'YouXam/Notion-GitHub-Sync'
        path: "notion-sync"
  
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml notion2md notion_client python-dateutil

    - name: Sync Notion to Github
      shell: bash
      run: |
        python ${{ github.workspace }}/notion-sync/main.py ${{ github.workspace }}/github/ ${{ inputs.notion_token }} ${{ inputs.author }}

    - name: Commit and push if changes
      shell: bash
      run: |
        cd ${{ github.workspace }}/github/
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Sync Notion to GitHub by GitHub Action"
        git push
